import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import axios from 'axios'
import { useEffect, useState } from 'react'
import { StreamCard } from 'components/StreamCard/StreamCard'

export default function Home() {
  const streams = [
    'nowayzao',
    'wastzera',
    'teomewhy',
    'duffyfps',
    'sksfps',
    'rnakano',
    'liminhag0d',
    'barr4k',
    'leonadev',
    'casimito',
    'gaules'
  ]

  const [
    loading,
    setLoading
  ] = useState(true)

  const [
    onlineStreams,
    setOnlineStreams
  ] = useState([])

  useEffect(() => {
    axios.post(`/api/twitch`, { "username": streams }).then((response) => {
      const data = response.data
      let allStreams = []
      streams.map((stream) => {
        const streamInfo = data.filter(d => d.user_login == stream)
        allStreams.push({
          title: stream,
          live: streamInfo.length,
          info: streamInfo[0]
        })
      })

      allStreams.sort((a, b) => {
        if (a.live) return -1
        return 1
      })

      setLoading(false)
      setOnlineStreams(allStreams)
    })
  }, [])

  const renderStreamList = () => {
    if (loading) {
      return (
        <p>Loading</p>
      )
    }

    return onlineStreams.map(s => <StreamCard key={s.title} stream={s} />)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Twitch Streams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {renderStreamList()}
      </main>
    </div>
  )
}
