import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'

export default function Home() {
  const streams = [
    'nowayzao',
    'wastzera',
    'teomewhy',
    'duffyfps',
    'sksfps',
    'rnakano',
    'liminhag0d',
    'barr4k',
    'leonadev',
    'MenyeB'
  ]

  const [
    onlineStreams,
    setOnlineStreams
  ] = useState([])

  useEffect(() => {
    axios.post(`http://localhost:3000/api/twitch`, { "username": streams }).then((response) => {
      setOnlineStreams(response.data)
    })
  }, [])

  if (onlineStreams.length === 0) {
    return (
      <p>carregando</p>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Twitch Streams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {onlineStreams.map(stream => {
          return (
            <div
              key={stream.id}
              className={styles.card}>
              <h2>
                <a
                  href={`https://twitch.tv/${stream.user_name}`}
                  target="_blank"
                  rel='noreferrer'>{stream.user_login} {stream.type}
                </a>
              </h2>
              <p>{stream.title}</p>
            </div>
          )
        })}
      </main>
    </div>
  )
}
